// <auto-generated />
using System;
using EventsApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EventsApi.Migrations
{
    [DbContext(typeof(EventsDbContext))]
    [Migration("20251118091432_LocationAdded")]
    partial class LocationAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EventsApi.Data.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Annual technology conference featuring latest innovations",
                            EndDate = new DateTime(2025, 3, 17, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Tech Conference 2025",
                            StartDate = new DateTime(2025, 3, 15, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Description = "Interactive workshop to strengthen team collaboration",
                            EndDate = new DateTime(2025, 2, 20, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Team Building Workshop",
                            StartDate = new DateTime(2025, 2, 20, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Description = "Exciting launch event for our new product line",
                            EndDate = new DateTime(2025, 4, 10, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Product Launch",
                            StartDate = new DateTime(2025, 4, 10, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Description = "Professional development training for all staff",
                            EndDate = new DateTime(2025, 1, 25, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Training Session",
                            StartDate = new DateTime(2025, 1, 25, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
